version: '3.8'

services:
  frontend:
    build:
      context: ./ui
    container_name: aestheticui
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`130.238.146.150`) && PathPrefix(`/`)"  # Use 130.238.146.150 or IP
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
  
  backend:
    build: 
      context: ./backend
    container_name: aestheticbackend
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`130.238.146.150`) && PathPrefix(`/api`)"  # Use 130.238.146.150 or IP
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  mongodb:
    image: mongo:8
    restart: always
    container_name: aestheticdb
    volumes:
      - mongodb_data:/data/db 



  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.yourdomain.com`)"
      - "traefik.http.routers.traefik.rule=Host(`130.238.146.150`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=dashboard"

volumes:
  mongodb_data:
