api:
  dashboard: true  # Enable the Traefik dashboard

entryPoints:
  web:
    address: ":80"  # HTTP only
  dashboard:
    address: ":8080"  # HTTP only

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Only expose containers with `traefik.enable=true`